### ISSUE TITLE
can you make same project for Objective-C?

### ISSUE THREAD

**Issue by TrowZeeN** [szk-atmosphere/SABlurImageView#14]
Hi. it looks great job. Can you make same project for Objective-C?

**Comment by szk-atmosphere** [comment]
Thanks for your request.
Yes, of course! I'll try it in a few days.

**Comment by TrowZeeN** [comment]
I am looking forward to it

**Comment by szk-atmosphere** [comment]
Hi!
I've finished making Objective-C version.
You can use [SABlurImageViewObjc](https://github.com/szk-atmosphere/SABlurImageViewObjc).
